//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGTHUC
    {
        public string MaMon { get; set; }
        public string MaNL { get; set; }
        public Nullable<decimal> SoLuongTieuHao { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
    }
}
