//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON_BAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON_BAN()
        {
            this.CHITIET_HDB = new HashSet<CHITIET_HDB>();
        }
    
        public int MaHDB { get; set; }
        public string MaKH { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string TenDangNhap { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HDB> CHITIET_HDB { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
