//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON_NHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON_NHAP()
        {
            this.CHITIET_HDN = new HashSet<CHITIET_HDN>();
        }
    
        public int MaHDN { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string MaNCC { get; set; }
        public string TenDangNhap { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HDN> CHITIET_HDN { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
