//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_CuaHangNuocEntities : DbContext
    {
        public QL_CuaHangNuocEntities()
            : base("name=QL_CuaHangNuocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAI_MON> LOAI_MON { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<CHITIET_HDB> CHITIET_HDB { get; set; }
        public virtual DbSet<CHITIET_HDN> CHITIET_HDN { get; set; }
        public virtual DbSet<HOADON_BAN> HOADON_BAN { get; set; }
        public virtual DbSet<HOADON_NHAP> HOADON_NHAP { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<CONGTHUC> CONGTHUCs { get; set; }
        public virtual DbSet<NGUYENLIEU> NGUYENLIEUx { get; set; }
    }
}
